services:
  bhima:
    # image: ghcr.io/third-culture-software/bhima:latest
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-bhima}
      - DB_NAME=${DB_NAME:-bhima}
      - DB_PASS=${DB_PASS:-cbeec29bac2f7726e1355c5a5bf10f35963cac8e77ed763bf2}
      - CHROME_OPTIONS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:9.2
    restart: unless-stopped
    command:
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./server/models:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER:-bhima}
      - MYSQL_DATABASE=${DB_NAME:-bhima}
      - MYSQL_PASSWORD=${DB_PASS:-cbeec29bac2f7726e1355c5a5bf10f35963cac8e77ed763bf2}
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - backend

networks:
  backend:

volumes:
  mysqldata:
