name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v6 

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: reviewdog (eslint)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reviewdog/action-eslint@v1.34.0
        with:
          reporter: github-pr-review
          eslint_flags: ""

      - name: reviewdog (shellcheck)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reviewdog/action-shellcheck@v1.32.0
        with:
          reporter: github-pr-review

      # - name: reviewdog (stylelint)
      #   uses: reviewdog/action-stylelint@v1.30.2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-pr-review 
